version: '3.8'

services:
  app:
    build: .
    image: schedule-tracker-app:latest
    container_name: team_schedule    
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  redis_data: